use_frameworks!

platform :ios, '10.0'

target 'ResourceLoaderCache_Example' do
  pod 'ResourceLoaderCache', :path => '../'
  pod 'SnapKit'
  
  target 'ResourceLoaderCache_Tests' do
    inherit! :search_paths

    
  end
end
